apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: i6qdpz81n-go-gitops
  description: This is GitOps manifest for i6qdpz81n-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: i6qdpz81n-go
    janus-idp.io/tekton: i6qdpz81n-go 
    backstage.io/kubernetes-id: i6qdpz81n-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:i6qdpz81n-go
